spring:
  application:
    name: dubbo-consumer
  servlet:
    multipart:
      max-file-size: 5242880
      max-request-size: 5242880
  profiles:
    active:
      - dev

server:
  servlet:
    context-path: /${spring.application.name}
  port: 8072

mybatis:
  config-location: classpath:com/xpl/framework/config/spring-mybatis.xml
  mapper-locations: classpath:com/xpl/dao/mapper/*.xml


